"""Create table registers

Revision ID: 50e84be966b5
Revises: 
Create Date: 2022-10-05 19:57:12.815972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e84be966b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_register_address'), 'register', ['address'], unique=False)
    op.create_index(op.f('ix_register_id'), 'register', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_register_id'), table_name='register')
    op.drop_index(op.f('ix_register_address'), table_name='register')
    op.drop_table('register')
    # ### end Alembic commands ###
